<a href="https://colab.research.google.com/github/Fuad2e3/Maching-Learning/blob/main/Train_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lab Report 1: Preprocessing

Objective: Perform preprocessing on a Bangla SMS Spam Dataset.

Dataset: https://raw.githubusercontent.com/Ataullha/Machine-Learning-Lab/refs/heads/main/bangla_spam.csv

Steps: Data cleaning, punctuation removal, stopword removal, tokenization, stemming.
Result: Clean dataset ready for training.
Conclusion: Preprocessing improves model performance.

In [50]:
import numpy as np
import pandas as pd

In [51]:
Spam = pd.read_csv('/content/Spam/bangla_spam.csv')

In [52]:
Spam.head()

   type                                               text
0  spam  এই মেসেজটি শেয়ার করুন এবং জিতে নিন আকর্ষণীয় ...
1  spam  আপনার বন্ধুদের রেফার করুন এবং প্রতি রেফারেলে ২...
2   ham  ট্রানজ্যাকশন নম্বর R234321.1554.640085 20 টাকা...
3  spam  নতুন অফার! সীমিত সময়ের জন্য পণ্যের উপর ৯০% পর...
4   ham  নববর্ষের শুভেচ্ছা!! আল্লাহ আপনার সকল কষ্ট দূর ...

# **Data Cleaning**

In [53]:
Spam.isnull().sum()

type    0
text    0
dtype: int64

In [54]:
Spam.duplicated().sum()

np.int64(25)

In [55]:
Spam = Spam.drop_duplicates()
Spam

      type                                               text
0     spam  এই মেসেজটি শেয়ার করুন এবং জিতে নিন আকর্ষণীয় ...
1     spam  আপনার বন্ধুদের রেফার করুন এবং প্রতি রেফারেলে ২...
2      ham  ট্রানজ্যাকশন নম্বর R234321.1554.640085 20 টাকা...
3     spam  নতুন অফার! সীমিত সময়ের জন্য পণ্যের উপর ৯০% পর...
4      ham  নববর্ষের শুভেচ্ছা!! আল্লাহ আপনার সকল কষ্ট দূর ...
...    ...                                                ...
2597  spam   প্রতিদিন ১০০ টাকা জিততে চান? এখনই অংশগ্রহণ করুন!
2598  spam  মোবাইল অ্যাপ ডাউনলোড করুন এবং ৫০০ টাকা বোনাস পান!
2599  spam    নতুন গ্রাহকদের জন্য বিশেষ অফার, আজই উপভোগ করুন!
2600  spam  আপনার অ্যাকাউন্ট আপগ্রেড করুন এবং এক্সক্লুসিভ ...
2601  spam  বিশেষ ছাড়! ২৪ ঘন্টার মধ্যে অর্ডার করুন এবং ৩০...

[2577 rows x 2 columns]

# **Punctuation Removal**

In [56]:
Spam['text'] = Spam['text'].str.replace('[.,!?:;]', '')
Spam

      type                                               text
0     spam  এই মেসেজটি শেয়ার করুন এবং জিতে নিন আকর্ষণীয় ...
1     spam  আপনার বন্ধুদের রেফার করুন এবং প্রতি রেফারেলে ২...
2      ham  ট্রানজ্যাকশন নম্বর R234321.1554.640085 20 টাকা...
3     spam  নতুন অফার! সীমিত সময়ের জন্য পণ্যের উপর ৯০% পর...
4      ham  নববর্ষের শুভেচ্ছা!! আল্লাহ আপনার সকল কষ্ট দূর ...
...    ...                                                ...
2597  spam   প্রতিদিন ১০০ টাকা জিততে চান? এখনই অংশগ্রহণ করুন!
2598  spam  মোবাইল অ্যাপ ডাউনলোড করুন এবং ৫০০ টাকা বোনাস পান!
2599  spam    নতুন গ্রাহকদের জন্য বিশেষ অফার, আজই উপভোগ করুন!
2600  spam  আপনার অ্যাকাউন্ট আপগ্রেড করুন এবং এক্সক্লুসিভ ...
2601  spam  বিশেষ ছাড়! ২৪ ঘন্টার মধ্যে অর্ডার করুন এবং ৩০...

[2577 rows x 2 columns]

# **Stopword Removal**

In [57]:
stopwords = ['আমি','তুমি','এই','ওই','সে','এটা']
pattern = '|'.join(stopwords)
Spam['text'] = Spam['text'].str.replace(pattern, '')
Spam

      type                                               text
0     spam  এই মেসেজটি শেয়ার করুন এবং জিতে নিন আকর্ষণীয় ...
1     spam  আপনার বন্ধুদের রেফার করুন এবং প্রতি রেফারেলে ২...
2      ham  ট্রানজ্যাকশন নম্বর R234321.1554.640085 20 টাকা...
3     spam  নতুন অফার! সীমিত সময়ের জন্য পণ্যের উপর ৯০% পর...
4      ham  নববর্ষের শুভেচ্ছা!! আল্লাহ আপনার সকল কষ্ট দূর ...
...    ...                                                ...
2597  spam   প্রতিদিন ১০০ টাকা জিততে চান? এখনই অংশগ্রহণ করুন!
2598  spam  মোবাইল অ্যাপ ডাউনলোড করুন এবং ৫০০ টাকা বোনাস পান!
2599  spam    নতুন গ্রাহকদের জন্য বিশেষ অফার, আজই উপভোগ করুন!
2600  spam  আপনার অ্যাকাউন্ট আপগ্রেড করুন এবং এক্সক্লুসিভ ...
2601  spam  বিশেষ ছাড়! ২৪ ঘন্টার মধ্যে অর্ডার করুন এবং ৩০...

[2577 rows x 2 columns]

# **Tokenization**

In [58]:
Spam['tokens'] = Spam['text'].str.split()

Spam

,type,text,tokens
0,spam,এই মেসেজটি শেয়ার করুন এবং জিতে নিন আকর্ষণীয় ...,"[এই, মেসেজটি, শেয়ার, করুন, এবং, জিতে, নিন, আক..."
1,spam,আপনার বন্ধুদের রেফার করুন এবং প্রতি রেফারেলে ২...,"[আপনার, বন্ধুদের, রেফার, করুন, এবং, প্রতি, রেফ..."
2,ham,ট্রানজ্যাকশন নম্বর R234321.1554.640085 20 টাকা...,"[ট্রানজ্যাকশন, নম্বর, R234321.1554.640085, 20,..."
3,spam,নতুন অফার! সীমিত সময়ের জন্য পণ্যের উপর ৯০% পর...,"[নতুন, অফার!, সীমিত, সময়ের, জন্য, পণ্যের, উপর..."
4,ham,নববর্ষের শুভেচ্ছা!! আল্লাহ আপনার সকল কষ্ট দূর ...,"[নববর্ষের, শুভেচ্ছা!!, আল্লাহ, আপনার, সকল, কষ্..."
...,...,...,...
2597,spam,প্রতিদিন ১০০ টাকা জিততে চান? এখনই অংশগ্রহণ করুন!,"[প্রতিদিন, ১০০, টাকা, জিততে, চান?, এখনই, অংশগ্..."
2598,spam,মোবাইল অ্যাপ ডাউনলোড করুন এবং ৫০০ টাকা বোনাস পান!,"[মোবাইল, অ্যাপ, ডাউনলোড, করুন, এবং, ৫০০, টাকা,..."
2599,spam,"নতুন গ্রাহকদের জন্য বিশেষ অফার, আজই উপভোগ করুন!","[নতুন, গ্রাহকদের, জন্য, বিশেষ, অফার,, আজই, উপভ..."
2600,spam,আপনার অ্যাকাউন্ট আপগ্রেড করুন এবং এক্সক্লুসিভ ...,"[আপনার, অ্যাকাউন্ট, আপগ্রেড, করুন, এবং, এক্সক্..."
2601,spam,বিশেষ ছাড়! ২৪ ঘন্টার মধ্যে অর্ডার করুন এবং ৩০...,"[বিশেষ, ছাড়!, ২৪, ঘন্টার, মধ্যে, অর্ডার, করুন..."

# **Stemming**

In [59]:
Spam['text'] = Spam['text'].str[:-1]
Spam

,type,text,tokens
0,spam,এই মেসেজটি শেয়ার করুন এবং জিতে নিন আকর্ষণীয় ...,"[এই, মেসেজটি, শেয়ার, করুন, এবং, জিতে, নিন, আক..."
1,spam,আপনার বন্ধুদের রেফার করুন এবং প্রতি রেফারেলে ২...,"[আপনার, বন্ধুদের, রেফার, করুন, এবং, প্রতি, রেফ..."
2,ham,ট্রানজ্যাকশন নম্বর R234321.1554.640085 20 টাকা...,"[ট্রানজ্যাকশন, নম্বর, R234321.1554.640085, 20,..."
3,spam,নতুন অফার! সীমিত সময়ের জন্য পণ্যের উপর ৯০% পর...,"[নতুন, অফার!, সীমিত, সময়ের, জন্য, পণ্যের, উপর..."
4,ham,নববর্ষের শুভেচ্ছা!! আল্লাহ আপনার সকল কষ্ট দূর ...,"[নববর্ষের, শুভেচ্ছা!!, আল্লাহ, আপনার, সকল, কষ্..."
...,...,...,...
2597,spam,প্রতিদিন ১০০ টাকা জিততে চান? এখনই অংশগ্রহণ করুন,"[প্রতিদিন, ১০০, টাকা, জিততে, চান?, এখনই, অংশগ্..."
2598,spam,মোবাইল অ্যাপ ডাউনলোড করুন এবং ৫০০ টাকা বোনাস পান,"[মোবাইল, অ্যাপ, ডাউনলোড, করুন, এবং, ৫০০, টাকা,..."
2599,spam,"নতুন গ্রাহকদের জন্য বিশেষ অফার, আজই উপভোগ করুন","[নতুন, গ্রাহকদের, জন্য, বিশেষ, অফার,, আজই, উপভ..."
2600,spam,আপনার অ্যাকাউন্ট আপগ্রেড করুন এবং এক্সক্লুসিভ ...,"[আপনার, অ্যাকাউন্ট, আপগ্রেড, করুন, এবং, এক্সক্..."
2601,spam,বিশেষ ছাড়! ২৪ ঘন্টার মধ্যে অর্ডার করুন এবং ৩০...,"[বিশেষ, ছাড়!, ২৪, ঘন্টার, মধ্যে, অর্ডার, করুন..."

Lab Report 2: Machine Learning

Objective: Apply Machine Learning model for classification.

Dataset: Same dataset as Lab Report 01.

Model: Naive Bayes.

Features: TF-IDF.

Result: Good accuracy achieved.

Conclusion: ML models work well with proper features.

In [60]:
from sklearn.model_selection import train_test_split

In [61]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder

In [70]:
from sklearn.naive_bayes import MultinomialNB

In [75]:
from sklearn.metrics import accuracy_score

In [62]:
x = Spam['tokens']
y = Spam['type']

In [63]:
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size = 0.2
)

# **TF--IDF (Multaple word to number convert)**

In [68]:
Number_convert = TfidfVectorizer(stop_words = stopwords)

# Run the algorithm
Number_convert.fit(x_train)

# Transfrom
xtr_scald = Number_convert.transform(x_train)
xts_scald = Number_convert.transform(x_test)

# **TF--IDF (word to number convert)**

In [69]:
le = LabelEncoder()

le.fit(y_train)

# Transfrom
ytr_scald = le.transform(y_train)
yts_scald = le.transform(y_test)

# **Model Apply**

In [71]:
nb_model = MultinomialNB()

# run
nb_model.fit(xtr_scald, ytr_scald)

MultinomialNB()

# **Score**

In [84]:
y_pred1 = nb_model.predict(xts_scald)

accuracy_score(yts_scald, y_pred1)*100

94.18604651162791